services:
  frontend:
    container_name: container_frontend
    build: 
     context: .
     target: production
     args:
     - NEXT_PUBLIC_API_URL_PROD=http://localhost:8080
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NEXT_WEBPACK_ENABLED=1
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - API_URL_INTERNAL=http://container_backend:8080
    stdin_open: true
    tty: true
    networks:
      - network_connect

networks:
  network_connect:
    external: true
