services:
  frontend:
    container_name: container_fronend
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NEXT_WEBPACK_ENABLED=1
      - API_URL=http://backend:8080
    stdin_open: true
    tty: true
    networks:
      - network_connect

networks:
  network_connect:
    external: true
