name: Build Front-End Production
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

    paths:
      - "**"
jobs:
  buil-deploy:
    name: Build And Production FrontEnd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check sysntax
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker
        uses: docker/login-action@v3
        with:
          username: "${{ secrets.DOCKER_ACCESS_USER}}"
          password: "${{ secrets.DOCKER_ACCESS_KEYS }}"

      - name: Build Docker Images
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          target: production
          dockerfile: Dockerfile
          tags: "autohunt-selling-car-frontend:${{ github.sha }}"
          env: NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL_PROD }}
            API_URL_INTERNAL=${{ secrets.API_URL_INTERNAL_PROD }}

      - name: Vulnerability Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "autohunt-selling-car-frontend:${{ github.sha }}"
          format: table
          exit-code: 1
          severity: CRITICAL

      - name: Push to Dockerhub
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: "${{ secrets.DOCKER_ACCESS_USER }}/autohunt-selling-car-frontend:${{ github.sha }}"
          cache-from: type=gha
          cache-to: type=gha, mode=max
